# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170221_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlines',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='sub_classifications',
            field=models.CharField(choices=[('Phones', 'Phones'), ('Geography', 'Geography'), ('History', 'History'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Sports', 'Sports'), ('Leisure', 'Sports'), ('Gadgets', 'Gadgets'), ('Computers', 'Computers')], default='Computers', max_length=200),
        ),
    ]
