# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170221_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlines',
            name='number_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Social', 'Social'), ('Tech', 'Tech'), ('Science', 'Science')], default='Tech', max_length=200),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='sub_classifications',
            field=models.CharField(choices=[('Leisure', 'Leisure'), ('Geography', 'Geography'), ('History', 'History'), ('Phones', 'Phones'), ('Biology', 'Biology'), ('Sports', 'Sports'), ('Gadgets', 'Gadgets'), ('Physics', 'Physics'), ('Computers', 'Computers')], default='Computers', max_length=200),
        ),
    ]
