# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170222_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Science', 'Science'), ('Social', 'Social')], default='Tech', max_length=200),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='sub_classifications',
            field=models.CharField(choices=[('History', 'History'), ('Gadgets', 'Gadgets'), ('Leisure', 'Leisure'), ('Geography', 'Geography'), ('Physics', 'Physics'), ('Sports', 'Sports'), ('Biology', 'Biology'), ('Phones', 'Phones'), ('Computers', 'Computers')], default='Computers', max_length=200),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='title',
            field=models.CharField(max_length=110),
        ),
    ]
