# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170222_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headlines',
            name='sub_classifications',
        ),
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Social', 'Social'), ('Tech', 'Tech'), ('Science', 'Science')], default='Tech', max_length=200),
        ),
    ]
