# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20170225_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlines',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Science', 'Science'), ('Tech', 'Tech'), ('Social', 'Social')], default='Tech', max_length=200),
        ),
    ]
