# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50)),
                ('comment_text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Social', 'Social'), ('Tech', 'Tech'), ('Science', 'Science')], default='Tech', max_length=200),
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
