# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20170226_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Science', 'Science'), ('Social', 'Social'), ('Tech', 'Tech')], default='Tech', max_length=200),
        ),
    ]
