# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20170227_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Social', 'Social'), ('Science', 'Science'), ('Tech', 'Tech')], default='Tech', max_length=200),
        ),
    ]
