# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20170227_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Science', 'Science'), ('Tech', 'Tech'), ('Social', 'Social')], default='Tech', max_length=200),
        ),
    ]
