# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20170227_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Science', 'Science'), ('Tech', 'Tech'), ('Social', 'Social')], default='Tech', max_length=200),
        ),
    ]
