# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20170228_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_comment',
            name='reference',
            field=models.IntegerField(default=0),
        ),
    ]
