# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20170304_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='classifications',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Science', 'Science'), ('Social', 'Social')], default='Tech', max_length=200),
        ),
    ]
